CREATE TABLE `users` (
	`id` INT(25) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`first_name` VARCHAR(70) NOT NULL,
	`last_name` VARCHAR(70) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL);
